#!/bin/bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
ROOT_DIR="$(dirname "$SCRIPT_DIR")"
SHARED_DIR="$ROOT_DIR/extensions/shared"
CHROME_DIR="$ROOT_DIR/extensions/chrome"
FIREFOX_DIR="$ROOT_DIR/extensions/firefox"

HEADER="// Generated by build-extensions.sh — do not edit directly.
// Source: extensions/shared/
"

echo "$HEADER" > "$CHROME_DIR/background.js"
cat "$SHARED_DIR/adapter-chrome.js" "$SHARED_DIR/core.js" >> "$CHROME_DIR/background.js"
echo "Built Chrome extension -> extensions/chrome/background.js"

echo "$HEADER" > "$FIREFOX_DIR/background.js"
cat "$SHARED_DIR/adapter-firefox.js" "$SHARED_DIR/core.js" >> "$FIREFOX_DIR/background.js"
echo "Built Firefox extension -> extensions/firefox/background.js"
